name: Configure and maintain the repo

on: [push]

permissions: write-all

jobs:
  configure:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          
      - run: |
          echo "REPOSITORY_NAME=$(
            echo '${{ github.repository }}' \
            | awk -F '/' '{print $2}' \
            | tr '-' '_' \
            | tr '[:upper:]' '[:lower:]' \
          )" >> $GITHUB_ENV

      - run: echo "REPOSITORY_URLNAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - run: echo "REPOSITORY_OWNER=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
        
      - run: echo "IS_TEMPLATE=$(ls .github/template.yml &> /dev/null && echo true || echo false)" >> $GITHUB_ENV
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Test configuration
        if: env.IS_TEMPLATE == 'true'
        run: |
          echo "Repo owner: ${{ env.REPOSITORY_OWNER }}"
          echo "Repo name: ${{ env.REPOSITORY_NAME }}"
          echo "Repo URL: ${{ env.REPOSITORY_URLNAME }}"
          echo "Template: ${{ env.IS_TEMPLATE }}"

          export SKIP_TLS_CHECK="False"
          export MTASTS_DOMAIN="digital.cabinet-office.gov.uk"
          python bin/configure.py

          cat CNAME
          cat .well-known/*

      - name: Push changes
        if: env.IS_TEMPLATE != 'true'
        run: |
          echo "Would push changes..."
