name: Configure and maintain the repo

on: [push]

permissions: write-all

jobs:
  config-and-maintain:
    #if: ${{ !contains (github.repository, '/mta-sts-template') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          
      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}' | tr '-' '_' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_URLNAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_OWNER=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
        shell: bash
        
      - name: Is this still a template
        id: is_template
        run: echo "::set-output name=is_template::$(ls .github/template.yml &> /dev/null && echo true || echo false)"

      - name: Rename the project
        # if: steps.is_template.outputs.is_template == 'true'
        run: |
          echo "Repo owner: ${{ env.REPOSITORY_OWNER }}"
          echo "Repo name: ${{ env.REPOSITORY_NAME }}"
          echo "Repo URL: ${{ env.REPOSITORY_URLNAME }}"
          echo "Template: ${{ steps.is_template.outputs.is_template }}"
